### PR TITLE
Change code style

### PR DESCRIPTION
**Pull request by giverplay**
With the evolution of the internet, much has been discussed about code styling, which has contributed to the uniform development of web technologies.
Based on that, I make improvements to the code, making it a little more webnastic.

### CODE REVIEW

**Comment by guilhermenevesxyz** [comment]
Thank you for your contribution!

Your code has the potential to be merged into the main repository. We just need to ask you a couple of things before that.

1. Since you made the usage of spaces instead of tabs very consistent within the JavaScript files, could you make it for the JSON file as well?
2. If you haven't checked the output of [iamawesome.com](https://iamawesome.com/), please do it and send it to us, so that we can check your aptitude.

Have a nice day!

**Comment by giverplay** [comment]
1 - Right, I'll replace the tabs with spaces.
2 - I'm awesome, I'm able to make changes.

**Comment by guilhermenevesxyz** [comment]
Just a last question: why did you replace the const function with a normal function? Is it slower?

**Comment by giverplay** [comment]
No performance issues.

**Comment by guilhermenevesxyz** [comment]
> No performance issues.

What's the point then?

**Comment by giverplay** [comment]
Readability.

**Comment by guilhermenevesxyz** [comment]
> Readability.

Welp, that's something we can't accept!

**Comment by guilhermenevesxyz** [comment]
We'll let this one pass, even though it does not match our standards completely.

Thanks again for your contribution!

**Pull request merged**
